logging:
  level:
    org.springframework.security: INFO

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

security:
  oauth2:
    resource:
      userInfoUri: http://localhost:5000/uaa/users/current
      
spring:
  rabbitmq:
    host: localhost
    port: 5672

---
spring:
  profiles: qa
  rabbitmq:
    host: rabbitmq

security:
  oauth2:
    resource:
      userInfoUri: http://auth-service:5000/uaa/users/current

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://registry:8761/eureka/
