
#

spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: system
    password: motive
    # Keep the connection alive if idle for a long time (needed in production)
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    # Show or not log for each sql query
    show-sql: false
    
logging:
    file: C:\Users\amercado\logs\serviceUser\serviceUserInfo.log
    destination:
      host: localhost
      port: 512
    pattern:
      console: "%d %-5level %logger : %msg%n"
      file: "%d %-5level [%thread] %logger : %msg%n"
    level:
      org.springframework.web: DEBUG
      guru.springframework.controllers: DEBUG
      org.hibernate: DEBUG
  
server:
  port: 8084
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  
